spring.application.name=mongo-demo

spring.mongodb.uri=mongodb+srv://kusuma9325_db_user:Kusuma%40123@productcluster.a5cm4nw.mongodb.net/product_catalogue?retryWrites=true&w=majority&appName=ProductCluster

server.port=8080